window.EcoSaveProducts = [
  {
    "id": "rau-muong-300g",
    "name": "Rau muống 300g",
    "category": "Vegetables",
    "originalPrice": 12000,
    "salePrice": 4000,
    "discountPercentage": 65,
    "expiryDate": "2026-07-31",
    "storeName": "36 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRS4DdEeRnPzb9eApJxSm_hCoDYBxmjQNq-tkq8Gqhj9Q&s=10",
    "description": "Sản phẩm cận hạn Rau muống 300g từ 36 Mart. Nhận hàng tại Hạ Bằng.",
    "quantity": 10,
    "location": "Hạ Bằng",
    "distance": 0
  },
  {
    "id": "cai-ngot-300g",
    "name": "Cải ngọt 300g",
    "category": "Vegetables",
    "originalPrice": 15000,
    "salePrice": 4000,
    "discountPercentage": 75,
    "expiryDate": "2026-07-31",
    "storeName": "37 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWnfr9D1M9rDk0YX3d7JdXyPuuVVYWmuizZ6TaSJwH6Q&s=10",
    "description": "Sản phẩm cận hạn Cải ngọt 300g từ 37 Mart. Nhận hàng tại Hạ Bằng.",
    "quantity": 10,
    "location": "Hạ Bằng",
    "distance": 0
  },
  {
    "id": "cai-thia-300g",
    "name": "Cải thìa 300g",
    "category": "Vegetables",
    "originalPrice": 18000,
    "salePrice": 9000,
    "discountPercentage": 52,
    "expiryDate": "2026-07-31",
    "storeName": "38 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQA5h7H_hwHVO_g19TvuANk_Cn6Xu-0zHyBadZQy5rx7A&s=10",
    "description": "Sản phẩm cận hạn Cải thìa 300g từ 38 Mart. Nhận hàng tại Hạ Bằng.",
    "quantity": 10,
    "location": "Hạ Bằng",
    "distance": 0
  },
  {
    "id": "xa-lach-romaine-300g",
    "name": "Xà lách Romaine 300g",
    "category": "Vegetables",
    "originalPrice": 28000,
    "salePrice": 11000,
    "discountPercentage": 60,
    "expiryDate": "2026-07-30",
    "storeName": "39 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLSgtLhurvSH6Z4Cr78K7HbM867kf2YnQLXBqwq6KJRA&s=10",
    "description": "Sản phẩm cận hạn Xà lách Romaine 300g từ 39 Mart. Nhận hàng tại Hạ Bằng.",
    "quantity": 10,
    "location": "Hạ Bằng",
    "distance": 0
  },
  {
    "id": "xa-lach-lollo-xanh",
    "name": "Xà lách Lollo xanh",
    "category": "Vegetables",
    "originalPrice": 32000,
    "salePrice": 8000,
    "discountPercentage": 75,
    "expiryDate": "2026-08-03",
    "storeName": "40 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1HFuAidJ6VgBPKGd1nPre9fEfGppO3Nj89RwJzsDtkw&s=10",
    "description": "Sản phẩm cận hạn Xà lách Lollo xanh từ 40 Mart. Nhận hàng tại Hạ Bằng.",
    "quantity": 10,
    "location": "Hạ Bằng",
    "distance": 0
  },
  {
    "id": "cai-bo-xoi-250g",
    "name": "Cải bó xôi 250g",
    "category": "Vegetables",
    "originalPrice": 30000,
    "salePrice": 4000,
    "discountPercentage": 85,
    "expiryDate": "2026-08-02",
    "storeName": "41 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdynJ7VQvHNQCHPX1A9SqYwFmf01Msbs2T600SyG-3fg&s=10",
    "description": "Sản phẩm cận hạn Cải bó xôi 250g từ 41 Mart. Nhận hàng tại Hạ Bằng.",
    "quantity": 10,
    "location": "Hạ Bằng",
    "distance": 0
  },
  {
    "id": "rau-mong-toi-300g",
    "name": "Rau mồng tơi 300g",
    "category": "Vegetables",
    "originalPrice": 14000,
    "salePrice": 4000,
    "discountPercentage": 75,
    "expiryDate": "2026-08-02",
    "storeName": "42 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0rq9RlvaG8omhQit0dyJR_lAeLkOaPKAaEMkoE_I7Tg&s=10",
    "description": "Sản phẩm cận hạn Rau mồng tơi 300g từ 42 Mart. Nhận hàng tại Hạ Bằng.",
    "quantity": 10,
    "location": "Hạ Bằng",
    "distance": 0
  },
  {
    "id": "rau-den-300g",
    "name": "Rau dền 300g",
    "category": "Vegetables",
    "originalPrice": 15000,
    "salePrice": 6000,
    "discountPercentage": 60,
    "expiryDate": "2026-07-28",
    "storeName": "43 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6zu4TZIjbnI1x4FgpozK1LG6z0s7UaMD4aM0nR-kBTw&s=10",
    "description": "Sản phẩm cận hạn Rau dền 300g từ 43 Mart. Nhận hàng tại Lục Quân.",
    "quantity": 10,
    "location": "Lục Quân",
    "distance": 0
  },
  {
    "id": "ca-chua-bi-da-lat-500g",
    "name": "Cà chua bi Đà Lạt 500g",
    "category": "Vegetables",
    "originalPrice": 32000,
    "salePrice": 16000,
    "discountPercentage": 50,
    "expiryDate": "2026-07-29",
    "storeName": "44 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBjftoIzQXwn5RQI6oZiExpHpj5HGwXTbHuEnUq_tTpg&s=10",
    "description": "Sản phẩm cận hạn Cà chua bi Đà Lạt 500g từ 44 Mart. Nhận hàng tại Lục Quân.",
    "quantity": 10,
    "location": "Lục Quân",
    "distance": 0
  },
  {
    "id": "dua-leo-baby-500g",
    "name": "Dưa leo baby 500g",
    "category": "Vegetables",
    "originalPrice": 22000,
    "salePrice": 9000,
    "discountPercentage": 58,
    "expiryDate": "2026-07-29",
    "storeName": "38 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLx_dqHoVD2B1IsHxbTIPPtDuOUGMe6lrAh5wP4-unxQ&s=10",
    "description": "Sản phẩm cận hạn Dưa leo baby 500g từ 38 Mart. Nhận hàng tại Lục Quân.",
    "quantity": 10,
    "location": "Lục Quân",
    "distance": 0
  },
  {
    "id": "bong-cai-xanh-500g",
    "name": "Bông cải xanh 500g",
    "category": "Vegetables",
    "originalPrice": 39000,
    "salePrice": 8000,
    "discountPercentage": 80,
    "expiryDate": "2026-07-28",
    "storeName": "39 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTfv8GYW8LToAD0qA4BjRYSjQvt07dfnY7ycwRFAR8jQ&s=10",
    "description": "Sản phẩm cận hạn Bông cải xanh 500g từ 39 Mart. Nhận hàng tại Lục Quân.",
    "quantity": 10,
    "location": "Lục Quân",
    "distance": 0
  },
  {
    "id": "ca-rot-da-lat-500g",
    "name": "Cà rốt Đà Lạt 500g",
    "category": "Vegetables",
    "originalPrice": 18000,
    "salePrice": 9000,
    "discountPercentage": 50,
    "expiryDate": "2026-07-28",
    "storeName": "40 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSD3ZkSIkaJMEf1p69ZySWCiTdffvrse2lR6krq_MSGfg&s=10",
    "description": "Sản phẩm cận hạn Cà rốt Đà Lạt 500g từ 40 Mart. Nhận hàng tại Lục Quân.",
    "quantity": 10,
    "location": "Lục Quân",
    "distance": 0
  },
  {
    "id": "khoai-tay-da-lat-1kg",
    "name": "Khoai tây Đà Lạt 1kg",
    "category": "Vegetables",
    "originalPrice": 32000,
    "salePrice": 14000,
    "discountPercentage": 55,
    "expiryDate": "2026-08-03",
    "storeName": "41 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQWqEsHJJb48waozUT7jnFu6hnZ4lkRtIP9HLOCcuD8hQ&s=10",
    "description": "Sản phẩm cận hạn Khoai tây Đà Lạt 1kg từ 41 Mart. Nhận hàng tại Lục Quân.",
    "quantity": 10,
    "location": "Lục Quân",
    "distance": 0
  },
  {
    "id": "nam-kim-cham-200g",
    "name": "Nấm kim châm 200g",
    "category": "Vegetables",
    "originalPrice": 12000,
    "salePrice": 6000,
    "discountPercentage": 50,
    "expiryDate": "2026-07-28",
    "storeName": "42 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT3AE_sxN3-gnaXQnLWppU5a2m5taMYfB3M3J6Tk8TxXA&s=10",
    "description": "Sản phẩm cận hạn Nấm kim châm 200g từ 42 Mart. Nhận hàng tại Lục Quân.",
    "quantity": 10,
    "location": "Lục Quân",
    "distance": 0
  },
  {
    "id": "nam-dui-ga-300g",
    "name": "Nấm đùi gà 300g",
    "category": "Vegetables",
    "originalPrice": 35000,
    "salePrice": 15000,
    "discountPercentage": 58,
    "expiryDate": "2026-08-02",
    "storeName": "36 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQL7gi-ERaHerObjS2aKrTlZ9SNlMhUwWhCmDf4pkIAsQ&s=10",
    "description": "Sản phẩm cận hạn Nấm đùi gà 300g từ 36 Mart. Nhận hàng tại Sơn Đông.",
    "quantity": 10,
    "location": "Sơn Đông",
    "distance": 0
  },
  {
    "id": "uc-ga-cp-500g",
    "name": "Ức gà CP 500g",
    "category": "Meat",
    "originalPrice": 59000,
    "salePrice": 15000,
    "discountPercentage": 75,
    "expiryDate": "2026-07-28",
    "storeName": "36 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT0Vw_MXvZ3jreeqFA17Ric2orT3reWupZIU4FSM_v1Nw&s=10",
    "description": "Sản phẩm cận hạn Ức gà CP 500g từ 36 Mart. Nhận hàng tại Sơn Đông.",
    "quantity": 10,
    "location": "Sơn Đông",
    "distance": 0
  },
  {
    "id": "dui-toi-ga-cp-500g",
    "name": "Đùi tỏi gà CP 500g",
    "category": "Meat",
    "originalPrice": 39000,
    "salePrice": 8000,
    "discountPercentage": 80,
    "expiryDate": "2026-07-31",
    "storeName": "37 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4CEmGjEcI7cQ3duxqQr0sgfeE-gh5DyXqqI7ytWOvrw&s=10",
    "description": "Sản phẩm cận hạn Đùi tỏi gà CP 500g từ 37 Mart. Nhận hàng tại Sơn Đông.",
    "quantity": 10,
    "location": "Sơn Đông",
    "distance": 0
  },
  {
    "id": "canh-ga-cp-500g",
    "name": "Cánh gà CP 500g",
    "category": "Meat",
    "originalPrice": 62000,
    "salePrice": 9000,
    "discountPercentage": 85,
    "expiryDate": "2026-07-30",
    "storeName": "38 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwxLMAjX9pk0z-4h9Upy9hptwGKr_hiqxdkIMNVRJd5A&s=10",
    "description": "Sản phẩm cận hạn Cánh gà CP 500g từ 38 Mart. Nhận hàng tại Sơn Đông.",
    "quantity": 10,
    "location": "Sơn Đông",
    "distance": 0
  },
  {
    "id": "ba-chi-heo-meatdeli-500g",
    "name": "Ba chỉ heo MeatDeli 500g",
    "category": "Meat",
    "originalPrice": 99000,
    "salePrice": 50000,
    "discountPercentage": 50,
    "expiryDate": "2026-07-31",
    "storeName": "39 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBmihCXJa5YChEpfws5sJyKxGhX7u_ytYVZWeB70VVwg&s=10",
    "description": "Sản phẩm cận hạn Ba chỉ heo MeatDeli 500g từ 39 Mart. Nhận hàng tại Sơn Đông.",
    "quantity": 10,
    "location": "Sơn Đông",
    "distance": 0
  },
  {
    "id": "nac-vai-meatdeli-500g",
    "name": "Nạc vai MeatDeli 500g",
    "category": "Meat",
    "originalPrice": 92000,
    "salePrice": 23000,
    "discountPercentage": 75,
    "expiryDate": "2026-07-30",
    "storeName": "40 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ9BruEWDRFjFxRbT1JaeYDIKG-HAapPR0NS9_WvbaNmg&s=10",
    "description": "Sản phẩm cận hạn Nạc vai MeatDeli 500g từ 40 Mart. Nhận hàng tại Sơn Đông.",
    "quantity": 10,
    "location": "Sơn Đông",
    "distance": 0
  },
  {
    "id": "thit-xay-meatdeli-300g",
    "name": "Thịt xay MeatDeli 300g",
    "category": "Meat",
    "originalPrice": 49000,
    "salePrice": 24000,
    "discountPercentage": 52,
    "expiryDate": "2026-07-30",
    "storeName": "41 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQi4CXyqIrHFRzidJgJiUOX9VHDtPtMCmpoDzkJ-YIzew&s=10",
    "description": "Sản phẩm cận hạn Thịt xay MeatDeli 300g từ 41 Mart. Nhận hàng tại Sơn Đông.",
    "quantity": 10,
    "location": "Sơn Đông",
    "distance": 0
  },
  {
    "id": "suon-non-heo-500g",
    "name": "Sườn non heo 500g",
    "category": "Meat",
    "originalPrice": 139000,
    "salePrice": 49000,
    "discountPercentage": 65,
    "expiryDate": "2026-07-31",
    "storeName": "42 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyfF5mHYuNh0tNKWDdAm9s7lgKllSRPCWNpNpw04YpvA&s=10",
    "description": "Sản phẩm cận hạn Sườn non heo 500g từ 42 Mart. Nhận hàng tại Sơn Tây.",
    "quantity": 10,
    "location": "Sơn Tây",
    "distance": 0
  },
  {
    "id": "bo-uc-cat-lat-300g",
    "name": "Bò Úc cắt lát 300g",
    "category": "Meat",
    "originalPrice": 169000,
    "salePrice": 81000,
    "discountPercentage": 52,
    "expiryDate": "2026-07-31",
    "storeName": "36 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQ3QvZt3jqrLafj2taIBZ-g63rasJIffdm9CQ1chy55Q&s",
    "description": "Sản phẩm cận hạn Bò Úc cắt lát 300g từ 36 Mart. Nhận hàng tại Sơn Tây.",
    "quantity": 10,
    "location": "Sơn Tây",
    "distance": 0
  },
  {
    "id": "bo-my-shabu-300g",
    "name": "Bò Mỹ shabu 300g",
    "category": "Meat",
    "originalPrice": 179000,
    "salePrice": 72000,
    "discountPercentage": 60,
    "expiryDate": "2026-08-01",
    "storeName": "37 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQXOf0OU0o_Ag9uM6a5EDdkZUc_t4LWWftpBIAGfyiGQ&s=10",
    "description": "Sản phẩm cận hạn Bò Mỹ shabu 300g từ 37 Mart. Nhận hàng tại Sơn Tây.",
    "quantity": 10,
    "location": "Sơn Tây",
    "distance": 0
  },
  {
    "id": "ca-hoi-phi-le-300g",
    "name": "Cá hồi phi lê 300g",
    "category": "Meat",
    "originalPrice": 199000,
    "salePrice": 96000,
    "discountPercentage": 52,
    "expiryDate": "2026-07-30",
    "storeName": "38 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdiXpSPY2dsfChwGTWqcufPEv1BQYafKCdMs0C4oeURg&s=10",
    "description": "Sản phẩm cận hạn Cá hồi phi lê 300g từ 38 Mart. Nhận hàng tại Sơn Tây.",
    "quantity": 10,
    "location": "Sơn Tây",
    "distance": 0
  },
  {
    "id": "ca-basa-phi-le-500g",
    "name": "Cá basa phi lê 500g",
    "category": "Meat",
    "originalPrice": 65000,
    "salePrice": 10000,
    "discountPercentage": 85,
    "expiryDate": "2026-08-01",
    "storeName": "39 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJ_JZLRIH3-mMXv4WNWm1n-0M8g9Uy75tQB02xB0WCkA&s=10",
    "description": "Sản phẩm cận hạn Cá basa phi lê 500g từ 39 Mart. Nhận hàng tại Sơn Tây.",
    "quantity": 10,
    "location": "Sơn Tây",
    "distance": 0
  },
  {
    "id": "ca-dieu-hong-lam-sach",
    "name": "Cá diêu hồng làm sạch",
    "category": "Meat",
    "originalPrice": 69000,
    "salePrice": 10000,
    "discountPercentage": 85,
    "expiryDate": "2026-08-02",
    "storeName": "40 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQfSGYAQ-9_2iLKxoRkpx3tOlO4G8VRmCqBUNnbccS6qg&s",
    "description": "Sản phẩm cận hạn Cá diêu hồng làm sạch từ 40 Mart. Nhận hàng tại Sơn Tây.",
    "quantity": 10,
    "location": "Sơn Tây",
    "distance": 0
  },
  {
    "id": "tom-the-500g",
    "name": "Tôm thẻ 500g",
    "category": "Meat",
    "originalPrice": 159000,
    "salePrice": 32000,
    "discountPercentage": 80,
    "expiryDate": "2026-08-04",
    "storeName": "41 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSeDS8TpIPHx9nzKHX46VaKyUucGrIM4-BzvKjTH0HdvA&s=10",
    "description": "Sản phẩm cận hạn Tôm thẻ 500g từ 41 Mart. Nhận hàng tại Sơn Tây.",
    "quantity": 10,
    "location": "Sơn Tây",
    "distance": 0
  },
  {
    "id": "muc-ong-lam-sach-500g",
    "name": "Mực ống làm sạch 500g",
    "category": "Meat",
    "originalPrice": 149000,
    "salePrice": 30000,
    "discountPercentage": 80,
    "expiryDate": "2026-07-29",
    "storeName": "42 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmKgUJXhKSHSj9F3zSojKExeHOAbcIgXZIdto5Y2w2nQ&s=10",
    "description": "Sản phẩm cận hạn Mực ống làm sạch 500g từ 42 Mart. Nhận hàng tại Tân Xã.",
    "quantity": 10,
    "location": "Tân Xã",
    "distance": 0
  },
  {
    "id": "cha-lua-vissan-500g",
    "name": "Chả lụa Vissan 500g",
    "category": "Meat",
    "originalPrice": 79000,
    "salePrice": 38000,
    "discountPercentage": 52,
    "expiryDate": "2026-08-02",
    "storeName": "36 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQu1hR6k7fxZys0fvTRKdSk0dtEtuOK5z32wz4r-G2d-g&s=10",
    "description": "Sản phẩm cận hạn Chả lụa Vissan 500g từ 36 Mart. Nhận hàng tại Tân Xã.",
    "quantity": 10,
    "location": "Tân Xã",
    "distance": 0
  },
  {
    "id": "ha-cao-tom-cau-tre-500g",
    "name": "Há cảo tôm Cầu Tre 500g",
    "category": "Frozen Food",
    "originalPrice": 62000,
    "salePrice": 9000,
    "discountPercentage": 85,
    "expiryDate": "2026-07-28",
    "storeName": "36 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQeCbUAKQKgYUbZzd7y-hLoucxzFhY8PvShuWXG77F7ZQ&s=10",
    "description": "Sản phẩm cận hạn Há cảo tôm Cầu Tre 500g từ 36 Mart. Nhận hàng tại Tân Xã.",
    "quantity": 10,
    "location": "Tân Xã",
    "distance": 0
  },
  {
    "id": "cha-gio-re-cau-tre",
    "name": "Chả giò rế Cầu Tre",
    "category": "Frozen Food",
    "originalPrice": 72000,
    "salePrice": 11000,
    "discountPercentage": 85,
    "expiryDate": "2026-08-04",
    "storeName": "37 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMv27juVWod2FEusbHeHvJdVz6NuGKLRsJWW_WcLmIOQ&s",
    "description": "Sản phẩm cận hạn Chả giò rế Cầu Tre từ 37 Mart. Nhận hàng tại Tân Xã.",
    "quantity": 10,
    "location": "Tân Xã",
    "distance": 0
  },
  {
    "id": "cha-gio-hai-san-cau-tre",
    "name": "Chả giò hải sản Cầu Tre",
    "category": "Frozen Food",
    "originalPrice": 78000,
    "salePrice": 39000,
    "discountPercentage": 50,
    "expiryDate": "2026-07-30",
    "storeName": "38 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_NyEjT7zb3GdUTPGdWcImJQedmdcDQu0lUBFmcBVZ8w&s=10",
    "description": "Sản phẩm cận hạn Chả giò hải sản Cầu Tre từ 38 Mart. Nhận hàng tại Tân Xã.",
    "quantity": 10,
    "location": "Tân Xã",
    "distance": 0
  },
  {
    "id": "ga-vien-chien-cp-500g",
    "name": "Gà viên chiên CP 500g",
    "category": "Frozen Food",
    "originalPrice": 99000,
    "salePrice": 35000,
    "discountPercentage": 65,
    "expiryDate": "2026-08-02",
    "storeName": "39 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQAr1okf10DRtTHPyNnEvEc-QISyn-2hHr61QEhftheKA&s=10",
    "description": "Sản phẩm cận hạn Gà viên chiên CP 500g từ 39 Mart. Nhận hàng tại Tân Xã.",
    "quantity": 10,
    "location": "Tân Xã",
    "distance": 0
  },
  {
    "id": "ca-vien-chien-cp-500g",
    "name": "Cá viên chiên CP 500g",
    "category": "Frozen Food",
    "originalPrice": 51000,
    "salePrice": 23000,
    "discountPercentage": 55,
    "expiryDate": "2026-08-04",
    "storeName": "40 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXlZRlM5VPF07oaWrupQf4i97adwiU5-M16FuN1RxB7A&s=10",
    "description": "Sản phẩm cận hạn Cá viên chiên CP 500g từ 40 Mart. Nhận hàng tại Tân Xã.",
    "quantity": 10,
    "location": "Tân Xã",
    "distance": 0
  },
  {
    "id": "xuc-xich-cp-cocktail",
    "name": "Xúc xích CP Cocktail",
    "category": "Frozen Food",
    "originalPrice": 85000,
    "salePrice": 26000,
    "discountPercentage": 70,
    "expiryDate": "2026-07-28",
    "storeName": "41 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZ2tnWl9ZimHs8Oy1eC46x8cMuuw-VZZjgvOrmA57lOg&s=10",
    "description": "Sản phẩm cận hạn Xúc xích CP Cocktail từ 41 Mart. Nhận hàng tại Thạch Hòa.",
    "quantity": 10,
    "location": "Thạch Hòa",
    "distance": 0
  },
  {
    "id": "bibigo-mandu-kimchi-525g",
    "name": "Bibigo Mandu Kimchi 525g",
    "category": "Frozen Food",
    "originalPrice": 109000,
    "salePrice": 33000,
    "discountPercentage": 70,
    "expiryDate": "2026-08-01",
    "storeName": "42 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWG2GiRCGs6vbCiPHDOKWGw_NqwYOvapxVAyI2r9sW_w&s",
    "description": "Sản phẩm cận hạn Bibigo Mandu Kimchi 525g từ 42 Mart. Nhận hàng tại Thạch Hòa.",
    "quantity": 10,
    "location": "Thạch Hòa",
    "distance": 0
  },
  {
    "id": "bibigo-mandu-thit-bo",
    "name": "Bibigo Mandu thịt bò",
    "category": "Frozen Food",
    "originalPrice": 115000,
    "salePrice": 17000,
    "discountPercentage": 85,
    "expiryDate": "2026-07-29",
    "storeName": "36 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSeyaJOodF90lQF0mhgfDU6T9GEJb9AK_0fdqEhz-aTVA&s=10",
    "description": "Sản phẩm cận hạn Bibigo Mandu thịt bò từ 36 Mart. Nhận hàng tại Thạch Hòa.",
    "quantity": 10,
    "location": "Thạch Hòa",
    "distance": 0
  },
  {
    "id": "hoanh-thanh-bibigo",
    "name": "Hoành thánh Bibigo",
    "category": "Frozen Food",
    "originalPrice": 99000,
    "salePrice": 40000,
    "discountPercentage": 60,
    "expiryDate": "2026-08-03",
    "storeName": "37 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQYZm1jGtv8u_VSB6DdqZ0TeJFl6twNfxsvIXLDGx7piQ&s=10",
    "description": "Sản phẩm cận hạn Hoành thánh Bibigo từ 37 Mart. Nhận hàng tại Thạch Hòa.",
    "quantity": 10,
    "location": "Thạch Hòa",
    "distance": 0
  },
  {
    "id": "pizza-hai-san-dong-lanh",
    "name": "Pizza Hải sản đông lạnh",
    "category": "Frozen Food",
    "originalPrice": 129000,
    "salePrice": 32000,
    "discountPercentage": 75,
    "expiryDate": "2026-07-29",
    "storeName": "38 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQSky78IHp9Sm2ZEa5rW1AHG6NWmi8L38H6G8crgiceyw&s=10",
    "description": "Sản phẩm cận hạn Pizza Hải sản đông lạnh từ 38 Mart. Nhận hàng tại Thạch Hòa.",
    "quantity": 10,
    "location": "Thạch Hòa",
    "distance": 0
  },
  {
    "id": "pizza-pepperoni-dong-lanh",
    "name": "Pizza Pepperoni đông lạnh",
    "category": "Frozen Food",
    "originalPrice": 129000,
    "salePrice": 45000,
    "discountPercentage": 65,
    "expiryDate": "2026-07-31",
    "storeName": "39 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-3RnFJ9Fsy-eIWhcNiUH_l1AWbzxWfu-0IrbhDNDXrg&s=10",
    "description": "Sản phẩm cận hạn Pizza Pepperoni đông lạnh từ 39 Mart. Nhận hàng tại Thạch Hòa.",
    "quantity": 10,
    "location": "Thạch Hòa",
    "distance": 0
  },
  {
    "id": "khoai-tay-farm-frites-1kg",
    "name": "Khoai tây Farm Frites 1kg",
    "category": "Frozen Food",
    "originalPrice": 95000,
    "salePrice": 46000,
    "discountPercentage": 52,
    "expiryDate": "2026-08-03",
    "storeName": "40 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSLiQlNBiXJBrigcgHq76WKNtVX8KoYSlrWCmNL_GUpiA&s=10",
    "description": "Sản phẩm cận hạn Khoai tây Farm Frites 1kg từ 40 Mart. Nhận hàng tại Thạch Hòa.",
    "quantity": 10,
    "location": "Thạch Hòa",
    "distance": 0
  },
  {
    "id": "khoai-tay-mccain-1kg",
    "name": "Khoai tây McCain 1kg",
    "category": "Frozen Food",
    "originalPrice": 119000,
    "salePrice": 54000,
    "discountPercentage": 55,
    "expiryDate": "2026-07-31",
    "storeName": "41 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSj59KCr7wwd9w9kRSRKt4qmhRZ2SFo8vt4lqFPMS4UIg&s=10",
    "description": "Sản phẩm cận hạn Khoai tây McCain 1kg từ 41 Mart. Nhận hàng tại Thôn 1 Hòa Lạc.",
    "quantity": 10,
    "location": "Thôn 1 Hòa Lạc",
    "distance": 0
  },
  {
    "id": "banh-bao-tho-phat-nhan-thit",
    "name": "Bánh bao Thọ Phát nhân thịt",
    "category": "Frozen Food",
    "originalPrice": 56000,
    "salePrice": 14000,
    "discountPercentage": 75,
    "expiryDate": "2026-07-29",
    "storeName": "42 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQX2teqCfB2SXIUi_nTKM3YtSbfyp18jJ8KYZjqLl8Ffg&s=10",
    "description": "Sản phẩm cận hạn Bánh bao Thọ Phát nhân thịt từ 42 Mart. Nhận hàng tại Thôn 1 Hòa Lạc.",
    "quantity": 10,
    "location": "Thôn 1 Hòa Lạc",
    "distance": 0
  },
  {
    "id": "banh-bao-tho-phat-xa-xiu",
    "name": "Bánh bao Thọ Phát xá xíu",
    "category": "Frozen Food",
    "originalPrice": 58000,
    "salePrice": 20000,
    "discountPercentage": 65,
    "expiryDate": "2026-08-01",
    "storeName": "36 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTG6ygfZ6eiQQvLeR7dWBIMKoQpxrOLtknRcVqlqU5B-A&s=10",
    "description": "Sản phẩm cận hạn Bánh bao Thọ Phát xá xíu từ 36 Mart. Nhận hàng tại Thôn 1 Hòa Lạc.",
    "quantity": 10,
    "location": "Thôn 1 Hòa Lạc",
    "distance": 0
  },
  {
    "id": "bo-vien-vissan-500g",
    "name": "Bò viên Vissan 500g",
    "category": "Frozen Food",
    "originalPrice": 79000,
    "salePrice": 12000,
    "discountPercentage": 85,
    "expiryDate": "2026-07-31",
    "storeName": "36 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSV6MBbUA_2-cSh9MBpIZtQ-KDw5ArZu8xFQQi2fz6luQ&s=10",
    "description": "Sản phẩm cận hạn Bò viên Vissan 500g từ 36 Mart. Nhận hàng tại Thôn 1 Hòa Lạc.",
    "quantity": 10,
    "location": "Thôn 1 Hòa Lạc",
    "distance": 0
  },
  {
    "id": "tom-tempura-dong-lanh",
    "name": "Tôm tempura đông lạnh",
    "category": "Frozen Food",
    "originalPrice": 179000,
    "salePrice": 75000,
    "discountPercentage": 58,
    "expiryDate": "2026-07-28",
    "storeName": "37 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRRsEQoin7vfa2-cl74oNwBHtcOGxK7QlCf2mCm03kDSw&s=10",
    "description": "Sản phẩm cận hạn Tôm tempura đông lạnh từ 37 Mart. Nhận hàng tại Thôn 1 Hòa Lạc.",
    "quantity": 10,
    "location": "Thôn 1 Hòa Lạc",
    "distance": 0
  },
  {
    "id": "ca-hoi-vien-400g",
    "name": "Cá hồi viên 400g",
    "category": "Frozen Food",
    "originalPrice": 99000,
    "salePrice": 30000,
    "discountPercentage": 70,
    "expiryDate": "2026-08-02",
    "storeName": "38 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTSq2m2C-BOrqmua2Hot5uNDSygAVywBxj9EiJtmCaK8Q&s=10",
    "description": "Sản phẩm cận hạn Cá hồi viên 400g từ 38 Mart. Nhận hàng tại Thôn 1 Hòa Lạc.",
    "quantity": 10,
    "location": "Thôn 1 Hòa Lạc",
    "distance": 0
  },
  {
    "id": "muc-vien-500g",
    "name": "Mực viên 500g",
    "category": "Frozen Food",
    "originalPrice": 68000,
    "salePrice": 33000,
    "discountPercentage": 52,
    "expiryDate": "2026-08-01",
    "storeName": "39 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSmgA1C5ESzbBXJC3CnV3Btkt0WwfU-UOefHfOW36pVHg&s=10",
    "description": "Sản phẩm cận hạn Mực viên 500g từ 39 Mart. Nhận hàng tại Thôn 1 Hòa Lạc.",
    "quantity": 10,
    "location": "Thôn 1 Hòa Lạc",
    "distance": 0
  },
  {
    "id": "thanh-cua-dong-lanh-250g",
    "name": "Thanh cua đông lạnh 250g",
    "category": "Frozen Food",
    "originalPrice": 49000,
    "salePrice": 17000,
    "discountPercentage": 65,
    "expiryDate": "2026-08-02",
    "storeName": "40 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR26jm3BRQSSV5ndorxA7aCyeyyLNC2-2SWp9eQPR77GQ&s",
    "description": "Sản phẩm cận hạn Thanh cua đông lạnh 250g từ 40 Mart. Nhận hàng tại Thôn 1 Hòa Lạc.",
    "quantity": 10,
    "location": "Thôn 1 Hòa Lạc",
    "distance": 0
  },
  {
    "id": "banh-mi-sandwich-otto",
    "name": "Bánh mì sandwich Otto",
    "category": "Bakery",
    "originalPrice": 38000,
    "salePrice": 19000,
    "discountPercentage": 50,
    "expiryDate": "2026-07-28",
    "storeName": "41 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpZbSUKXPDwA8wwK12N8UyEsaLePIUdgCEn7T3B8nYGg&s=10",
    "description": "Sản phẩm cận hạn Bánh mì sandwich Otto từ 41 Mart. Nhận hàng tại Thôn 2 Hòa Lạc.",
    "quantity": 10,
    "location": "Thôn 2 Hòa Lạc",
    "distance": 0
  },
  {
    "id": "banh-mi-nguyen-cam",
    "name": "Bánh mì nguyên cám",
    "category": "Bakery",
    "originalPrice": 45000,
    "salePrice": 7000,
    "discountPercentage": 85,
    "expiryDate": "2026-07-28",
    "storeName": "42 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTgk2A24kLIY2lDq76fkCaG8dhmtAOIp4bUF8Y_GLk2w&s=10",
    "description": "Sản phẩm cận hạn Bánh mì nguyên cám từ 42 Mart. Nhận hàng tại Thôn 2 Hòa Lạc.",
    "quantity": 10,
    "location": "Thôn 2 Hòa Lạc",
    "distance": 0
  },
  {
    "id": "banh-croissant-bo",
    "name": "Bánh Croissant bơ",
    "category": "Bakery",
    "originalPrice": 28000,
    "salePrice": 4000,
    "discountPercentage": 85,
    "expiryDate": "2026-07-28",
    "storeName": "36 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTi1T8WNdHJLBw6s1x4IGOdyq3sC5eVoWrVUM_U3tacbQ&s=10",
    "description": "Sản phẩm cận hạn Bánh Croissant bơ từ 36 Mart. Nhận hàng tại Thôn 2 Hòa Lạc.",
    "quantity": 10,
    "location": "Thôn 2 Hòa Lạc",
    "distance": 0
  },
  {
    "id": "donut-socola",
    "name": "Donut socola",
    "category": "Bakery",
    "originalPrice": 22000,
    "salePrice": 6000,
    "discountPercentage": 75,
    "expiryDate": "2026-08-03",
    "storeName": "37 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcoCtcK-mXGAOQsKS-KzjepUlDNeYZS7artKBLH0EdFw&s=10",
    "description": "Sản phẩm cận hạn Donut socola từ 37 Mart. Nhận hàng tại Thôn 2 Hòa Lạc.",
    "quantity": 10,
    "location": "Thôn 2 Hòa Lạc",
    "distance": 0
  },
  {
    "id": "th-true-milk-1l",
    "name": "TH True Milk 1L",
    "category": "Dairy",
    "originalPrice": 43900,
    "salePrice": 11000,
    "discountPercentage": 75,
    "expiryDate": "2026-08-03",
    "storeName": "40 Mart",
    "image": "https://suachobeyeu.vn/upload/images/sua-tuoi-th-true-milk-co-duong-hop-1-lit-4-2.jpg",
    "description": "Sản phẩm cận hạn TH True Milk 1L từ 40 Mart. Nhận hàng tại Thôn 2 Hòa Lạc.",
    "quantity": 10,
    "location": "Thôn 2 Hòa Lạc",
    "distance": 0
  },
  {
    "id": "vinamilk-green-farm-1l",
    "name": "Vinamilk Green Farm 1L",
    "category": "Dairy",
    "originalPrice": 42000,
    "salePrice": 10000,
    "discountPercentage": 75,
    "expiryDate": "2026-07-29",
    "storeName": "41 Mart",
    "image": "https://www.lottemart.vn/media/catalog/product/cache/0x0/8/9/8934673100595-1.jpg.webp",
    "description": "Sản phẩm cận hạn Vinamilk Green Farm 1L từ 41 Mart. Nhận hàng tại Thôn 2 Hòa Lạc.",
    "quantity": 10,
    "location": "Thôn 2 Hòa Lạc",
    "distance": 0
  },
  {
    "id": "sua-chua-vinamilk-khong-duong-4-hop",
    "name": "Sữa chua Vinamilk không đường (4 hộp)",
    "category": "Dairy",
    "originalPrice": 29000,
    "salePrice": 6000,
    "discountPercentage": 80,
    "expiryDate": "2026-08-02",
    "storeName": "42 Mart",
    "image": "https://bizweb.dktcdn.net/thumb/grande/100/112/377/products/screenshot-2020-06-17-sua-chua-an-vinamilk-khong-duong-vi-4-hop-x-100g.png?v=1592363802443",
    "description": "Sản phẩm cận hạn Sữa chua Vinamilk không đường (4 hộp) từ 42 Mart. Nhận hàng tại Thôn 3 Hòa Lạc.",
    "quantity": 10,
    "location": "Thôn 3 Hòa Lạc",
    "distance": 0
  },
  {
    "id": "sua-chua-th-true-yogurt",
    "name": "Sữa chua TH True Yogurt",
    "category": "Dairy",
    "originalPrice": 34000,
    "salePrice": 10000,
    "discountPercentage": 70,
    "expiryDate": "2026-07-30",
    "storeName": "36 Mart",
    "image": "https://product.hstatic.net/200000580015/product/loc_sc_it_dg_a19139ca62df48a484f05ad7ae12b12b_large.png",
    "description": "Sản phẩm cận hạn Sữa chua TH True Yogurt từ 36 Mart. Nhận hàng tại Thôn 3 Hòa Lạc.",
    "quantity": 10,
    "location": "Thôn 3 Hòa Lạc",
    "distance": 0
  },
  {
    "id": "pho-mai-con-bo-cuoi",
    "name": "Phô mai Con Bò Cười",
    "category": "Dairy",
    "originalPrice": 58000,
    "salePrice": 12000,
    "discountPercentage": 80,
    "expiryDate": "2026-07-28",
    "storeName": "36 Mart",
    "image": "https://bizweb.dktcdn.net/100/514/431/products/pho-mai-con-bo-cuoi-hop-112g-8-mieng-202307301319192465.jpg?v=1716297178740",
    "description": "Sản phẩm cận hạn Phô mai Con Bò Cười từ 36 Mart. Nhận hàng tại Thôn 3 Hòa Lạc.",
    "quantity": 10,
    "location": "Thôn 3 Hòa Lạc",
    "distance": 0
  },
  {
    "id": "bo-anchor-227g",
    "name": "Bơ Anchor 227g",
    "category": "Dairy",
    "originalPrice": 95000,
    "salePrice": 33000,
    "discountPercentage": 65,
    "expiryDate": "2026-07-29",
    "storeName": "37 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSmfIdGxg_jy1dMZjhEkR0dkBvZNH88jeL5hH5WbsF_rQ&s=10",
    "description": "Sản phẩm cận hạn Bơ Anchor 227g từ 37 Mart. Nhận hàng tại Thôn 3 Hòa Lạc.",
    "quantity": 10,
    "location": "Thôn 3 Hòa Lạc",
    "distance": 0
  },
  {
    "id": "banh-mi-sandwich-otto-2",
    "name": "Bánh mì sandwich Otto",
    "category": "Bakery",
    "originalPrice": 38000,
    "salePrice": 15000,
    "discountPercentage": 61,
    "expiryDate": "2026-07-30",
    "storeName": "38 Mart",
    "image": "https://phamnguyenfoods.com/wp-content/uploads/2022/09/245g.jpg",
    "description": "Sản phẩm cận hạn Bánh mì sandwich Otto từ 38 Mart. Nhận hàng tại Thôn 3 Hòa Lạc.",
    "quantity": 10,
    "location": "Thôn 3 Hòa Lạc",
    "distance": 0
  },
  {
    "id": "banh-mi-nguyen-cam-2",
    "name": "Bánh mì nguyên cám",
    "category": "Bakery",
    "originalPrice": 42000,
    "salePrice": 17000,
    "discountPercentage": 60,
    "expiryDate": "2026-07-31",
    "storeName": "39 Mart",
    "image": "https://file.hstatic.net/200000700229/article/lam-banh-mi-nguyen-cam-bang-noi-chien-khong-dau-1_cb542a73398049208ca2a04d6c79e504.jpg",
    "description": "Sản phẩm cận hạn Bánh mì nguyên cám từ 39 Mart. Nhận hàng tại Thôn 3 Hòa Lạc.",
    "quantity": 10,
    "location": "Thôn 3 Hòa Lạc",
    "distance": 0
  },
  {
    "id": "banh-croissant-bo-2",
    "name": "Bánh Croissant bơ",
    "category": "Bakery",
    "originalPrice": 28000,
    "salePrice": 7000,
    "discountPercentage": 75,
    "expiryDate": "2026-07-30",
    "storeName": "40 Mart",
    "image": "https://hakyo.vn/wp-content/uploads/2024/07/croissant_bo_toi-e1730816677697.png",
    "description": "Sản phẩm cận hạn Bánh Croissant bơ từ 40 Mart. Nhận hàng tại Thôn 3 Hòa Lạc.",
    "quantity": 10,
    "location": "Thôn 3 Hòa Lạc",
    "distance": 0
  },
  {
    "id": "donut-socola-2",
    "name": "Donut socola",
    "category": "Bakery",
    "originalPrice": 22000,
    "salePrice": 5000,
    "discountPercentage": 77,
    "expiryDate": "2026-07-31",
    "storeName": "41 Mart",
    "image": "https://i.pinimg.com/736x/57/82/85/578285d6e1f5b63c6eaf44932323a969.jpg",
    "description": "Sản phẩm cận hạn Donut socola từ 41 Mart. Nhận hàng tại Thôn 3 Hòa Lạc.",
    "quantity": 10,
    "location": "Thôn 3 Hòa Lạc",
    "distance": 0
  },
  {
    "id": "banh-su-kem",
    "name": "Bánh su kem",
    "category": "Bakery",
    "originalPrice": 35000,
    "salePrice": 12000,
    "discountPercentage": 66,
    "expiryDate": "2026-08-01",
    "storeName": "42 Mart",
    "image": "https://i.pinimg.com/1200x/55/a4/71/55a4719632349e004b2939ae80e6f7b7.jpg",
    "description": "Sản phẩm cận hạn Bánh su kem từ 42 Mart. Nhận hàng tại Thôn 4 Hòa Lạc.",
    "quantity": 10,
    "location": "Thôn 4 Hòa Lạc",
    "distance": 0
  },
  {
    "id": "banh-mi-pho-mai",
    "name": "Bánh mì phô mai",
    "category": "Bakery",
    "originalPrice": 32000,
    "salePrice": 9000,
    "discountPercentage": 72,
    "expiryDate": "2026-08-01",
    "storeName": "36 Mart",
    "image": "https://product.hstatic.net/200000849803/product/ph__mai_tan_ch_y-02_802571d022da48ef8679cb3dd2f95a54.png",
    "description": "Sản phẩm cận hạn Bánh mì phô mai từ 36 Mart. Nhận hàng tại Thôn 4 Hòa Lạc.",
    "quantity": 10,
    "location": "Thôn 4 Hòa Lạc",
    "distance": 0
  },
  {
    "id": "th-true-milk-1l-2",
    "name": "TH True Milk 1L",
    "category": "Drinks",
    "originalPrice": 43900,
    "salePrice": 13000,
    "discountPercentage": 70,
    "expiryDate": "2026-08-02",
    "storeName": "37 Mart",
    "image": "https://suachobeyeu.vn/upload/images/sua-tuoi-th-true-milk-co-duong-hop-1-lit-4-2.jpg",
    "description": "Sản phẩm cận hạn TH True Milk 1L từ 37 Mart. Nhận hàng tại Thôn 4 Hòa Lạc.",
    "quantity": 10,
    "location": "Thôn 4 Hòa Lạc",
    "distance": 0
  },
  {
    "id": "vinamilk-green-farm-1l-2",
    "name": "Vinamilk Green Farm 1L",
    "category": "Drinks",
    "originalPrice": 42000,
    "salePrice": 12000,
    "discountPercentage": 71,
    "expiryDate": "2026-08-02",
    "storeName": "38 Mart",
    "image": "https://www.lottemart.vn/media/catalog/product/cache/0x0/8/9/8934673101264-1-1.jpg.webp",
    "description": "Sản phẩm cận hạn Vinamilk Green Farm 1L từ 38 Mart. Nhận hàng tại Thôn 4 Hòa Lạc.",
    "quantity": 10,
    "location": "Thôn 4 Hòa Lạc",
    "distance": 0
  },
  {
    "id": "coca-cola-1-5l",
    "name": "Coca-Cola 1.5L",
    "category": "Drinks",
    "originalPrice": 24000,
    "salePrice": 8000,
    "discountPercentage": 67,
    "expiryDate": "2026-08-03",
    "storeName": "39 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQhmcfpYTAiS6l8OG89vWmBBXKeKyzUDMSEciDcHoFDWMPXkdipXNyAIdg&s=10",
    "description": "Sản phẩm cận hạn Coca-Cola 1.5L từ 39 Mart. Nhận hàng tại Thôn 4 Hòa Lạc.",
    "quantity": 10,
    "location": "Thôn 4 Hòa Lạc",
    "distance": 0
  },
  {
    "id": "pepsi-1-5l",
    "name": "Pepsi 1.5L",
    "category": "Drinks",
    "originalPrice": 23000,
    "salePrice": 7000,
    "discountPercentage": 70,
    "expiryDate": "2026-08-03",
    "storeName": "40 Mart",
    "image": "https://cdn.tgdd.vn/Products/Images/2443/76465/bhx/nuoc-ngot-pepsi-cola-chai-15-lit-202407081352122675.jpg",
    "description": "Sản phẩm cận hạn Pepsi 1.5L từ 40 Mart. Nhận hàng tại Thôn 4 Hòa Lạc.",
    "quantity": 10,
    "location": "Thôn 4 Hòa Lạc",
    "distance": 0
  },
  {
    "id": "tra-xanh-khong-do-455ml",
    "name": "Trà Xanh Không Độ 455ml",
    "category": "Drinks",
    "originalPrice": 12000,
    "salePrice": 4000,
    "discountPercentage": 67,
    "expiryDate": "2026-07-31",
    "storeName": "41 Mart",
    "image": "https://cdnv2.tgdd.vn/bhx-static/bhx/Products/Images/8938/85739/bhx/fgjiol_202410140914265805.jpg",
    "description": "Sản phẩm cận hạn Trà Xanh Không Độ 455ml từ 41 Mart. Nhận hàng tại Thôn 4 Hòa Lạc.",
    "quantity": 10,
    "location": "Thôn 4 Hòa Lạc",
    "distance": 0
  },
  {
    "id": "c2-tra-xanh-455ml",
    "name": "C2 Trà xanh 455ml",
    "category": "Drinks",
    "originalPrice": 11000,
    "salePrice": 3000,
    "discountPercentage": 73,
    "expiryDate": "2026-07-31",
    "storeName": "42 Mart",
    "image": "https://cdn.tgdd.vn/Products/Images/8938/76390/bhx/tra-xanh-c2-huong-chanh-455ml-202006191929206306.jpg",
    "description": "Sản phẩm cận hạn C2 Trà xanh 455ml từ 42 Mart. Nhận hàng tại Thôn 4 Hòa Lạc.",
    "quantity": 10,
    "location": "Thôn 4 Hòa Lạc",
    "distance": 0
  },
  {
    "id": "sting-dau-330ml",
    "name": "Sting Dâu 330ml",
    "category": "Drinks",
    "originalPrice": 12000,
    "salePrice": 4000,
    "discountPercentage": 67,
    "expiryDate": "2026-07-31",
    "storeName": "36 Mart",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSUOYGBN6u3cJrrbVInm4hWO11YcEt6_4X1jC7gfWN8q8Jr7fRJBoEYVUw&s=10",
    "description": "Sản phẩm cận hạn Sting Dâu 330ml từ 36 Mart. Nhận hàng tại Thôn 5 Hòa Lạc.",
    "quantity": 10,
    "location": "Thôn 5 Hòa Lạc",
    "distance": 0
  },
  {
    "id": "twister-cam-1l",
    "name": "Twister Cam 1L",
    "category": "Drinks",
    "originalPrice": 39000,
    "salePrice": 12000,
    "discountPercentage": 69,
    "expiryDate": "2026-08-02",
    "storeName": "36 Mart",
    "image": "https://www.lottemart.vn/media/catalog/product/cache/0x0/8/9/8934588193101-1_2.jpg.webp",
    "description": "Sản phẩm cận hạn Twister Cam 1L từ 36 Mart. Nhận hàng tại Thôn 5 Hòa Lạc.",
    "quantity": 10,
    "location": "Thôn 5 Hòa Lạc",
    "distance": 0
  },
  {
    "id": "oreo-original-133g",
    "name": "OREO Original 133g",
    "category": "Snacks",
    "originalPrice": 22000,
    "salePrice": 7000,
    "discountPercentage": 68,
    "expiryDate": "2026-08-03",
    "storeName": "37 Mart",
    "image": "https://cdn.tgdd.vn/Products/Images//3357/79860/bhx/files/banh-quy-nhan-kem-vani-oreo-goi-133g-202208031516537634.jpg",
    "description": "Sản phẩm cận hạn OREO Original 133g từ 37 Mart. Nhận hàng tại Thôn 5 Hòa Lạc.",
    "quantity": 10,
    "location": "Thôn 5 Hòa Lạc",
    "distance": 0
  },
  {
    "id": "pocky-chocolate",
    "name": "Pocky Chocolate",
    "category": "Snacks",
    "originalPrice": 18000,
    "salePrice": 5000,
    "discountPercentage": 72,
    "expiryDate": "2026-08-02",
    "storeName": "38 Mart",
    "image": "https://www.lottemart.vn/media/catalog/product/cache/0x0/8/8/8851019310244.jpg.webp",
    "description": "Sản phẩm cận hạn Pocky Chocolate từ 38 Mart. Nhận hàng tại Thôn 5 Hòa Lạc.",
    "quantity": 10,
    "location": "Thôn 5 Hòa Lạc",
    "distance": 0
  },
  {
    "id": "lay-s-original-95g",
    "name": "Lay's Original 95g",
    "category": "Snacks",
    "originalPrice": 27000,
    "salePrice": 8000,
    "discountPercentage": 70,
    "expiryDate": "2026-08-03",
    "storeName": "39 Mart",
    "image": "https://www.lottemart.vn/media/catalog/product/cache/0x0/8/9/8936079120139.jpg.webp",
    "description": "Sản phẩm cận hạn Lay's Original 95g từ 39 Mart. Nhận hàng tại Thôn 5 Hòa Lạc.",
    "quantity": 10,
    "location": "Thôn 5 Hòa Lạc",
    "distance": 0
  },
  {
    "id": "swing-bbq",
    "name": "Swing BBQ",
    "category": "Snacks",
    "originalPrice": 18000,
    "salePrice": 5000,
    "discountPercentage": 72,
    "expiryDate": "2026-08-01",
    "storeName": "40 Mart",
    "image": "https://www.lottemart.vn/media/catalog/product/cache/0x0/8/9/8936036021660.jpg.webp",
    "description": "Sản phẩm cận hạn Swing BBQ từ 40 Mart. Nhận hàng tại Thôn 5 Hòa Lạc.",
    "quantity": 10,
    "location": "Thôn 5 Hòa Lạc",
    "distance": 0
  },
  {
    "id": "oishi-pillows",
    "name": "Oishi Pillows",
    "category": "Snacks",
    "originalPrice": 19000,
    "salePrice": 6000,
    "discountPercentage": 68,
    "expiryDate": "2026-08-01",
    "storeName": "41 Mart",
    "image": "https://cdn.hstatic.net/products/200000495609/k-nhan-kem-pillows-sponge-oishi-du-vi-goi-85g-banh-keo-an-vat-imnuts-0_481bc353484e458786683faa7cb2778c_master.jpg",
    "description": "Sản phẩm cận hạn Oishi Pillows từ 41 Mart. Nhận hàng tại Thôn 5 Hòa Lạc.",
    "quantity": 10,
    "location": "Thôn 5 Hòa Lạc",
    "distance": 0
  },
  {
    "id": "custas-orion",
    "name": "Custas Orion",
    "category": "Snacks",
    "originalPrice": 38000,
    "salePrice": 9000,
    "discountPercentage": 76,
    "expiryDate": "2026-08-02",
    "storeName": "42 Mart",
    "image": "https://orion.vn/media/xcchisa4/custas_12p_mockup.png",
    "description": "Sản phẩm cận hạn Custas Orion từ 42 Mart. Nhận hàng tại Thôn 5Hòa Lạc.",
    "quantity": 10,
    "location": "Thôn 5Hòa Lạc",
    "distance": 0
  },
  {
    "id": "oreo-original-133g-2",
    "name": "OREO Original 133g",
    "category": "Snacks",
    "originalPrice": 22000,
    "salePrice": 7000,
    "discountPercentage": 68,
    "expiryDate": "2026-08-03",
    "storeName": "42 Mart",
    "image": "https://cdn.tgdd.vn/Products/Images//3357/79860/bhx/files/banh-quy-nhan-kem-vani-oreo-goi-133g-202208031516537634.jpg",
    "description": "Sản phẩm cận hạn OREO Original 133g từ 42 Mart. Nhận hàng tại Thôn 5 Hòa Lạc.",
    "quantity": 10,
    "location": "Thôn 5 Hòa Lạc",
    "distance": 0
  },
  {
    "id": "custas-orion-2",
    "name": "Custas Orion",
    "category": "Snacks",
    "originalPrice": 38000,
    "salePrice": 9000,
    "discountPercentage": 76,
    "expiryDate": "2026-08-02",
    "storeName": "42 Mart",
    "image": "https://www.google.com/search?q=Custas+Orion&udm=2#sv=CAMSURoyKhBlLV80ZnZPU3BreUdIenVNMg5fNGZ2T1Nwa3lHSHp1TToOMnp0RkhIU2U3LUFFV00gBCoXCgFzEhBlLV80ZnZPU3BreUdIenVNGAEwARgHIPqrl7gCSggQARgBIAEoAQ",
    "description": "Sản phẩm cận hạn Custas Orion từ 42 Mart. Nhận hàng tại Thôn 5Hòa Lạc.",
    "quantity": 10,
    "location": "Thôn 5Hòa Lạc",
    "distance": 0
  },
  {
    "id": "oreo-original-133g-3",
    "name": "OREO Original 133g",
    "category": "Snacks",
    "originalPrice": 22000,
    "salePrice": 7000,
    "discountPercentage": 68,
    "expiryDate": "2026-08-03",
    "storeName": "42 Mart",
    "image": "https://www.google.com/search?q=OREO+Original+133g&udm=2#sv=CAMSURoyKhBlLV9JTFE4MFIzQnVKdjVNMg5fSUxRODBSM0J1SnY1TToOVEIzTzV0UUdadHN4Sk0gBCoXCgFzEhBlLV9JTFE4MFIzQnVKdjVNGAEwARgHIMq9ybYKSggQARgBIAEoAQ",
    "description": "Sản phẩm cận hạn OREO Original 133g từ 42 Mart. Nhận hàng tại Thôn 5 Hòa Lạc.",
    "quantity": 10,
    "location": "Thôn 5 Hòa Lạc",
    "distance": 0
  }
];
